---
title: "Activity - Least Squares II"
output:
  rmarkdown::html_document:
  header-includes:
   - \usepackage{amsmath}
---

\renewcommand{\vec}[1]{\mathbf{#1}}
\renewcommand{\mat}[1]{\mathbf{#1}}

Remember to show your work / give your reasoning, as applicable.

```{r message=FALSE}
library(pracma)
```

### Problem 1

a\. Use the classical Gram-Schmidt orthogonalization algorithm to find the reduced **QR** factorization and full **QR** factorization of the matrix 

$$
\mat{A} = \begin{pmatrix}
2 & 3 \\
-2 & -6 \\
1 & 0
\end{pmatrix}.
$$

Don't use R's built-in `qr` function. Do the calculation by hand. However, you can certainly use R to carry out the algebra if you want.

b\. First check your answers by verifying that $\mat{A}=\mat{Q}\mat{R}$ and $\mat{A}=\overline{\mat{Q}}\overline{\mat{R}}$. Then check whether you computed the same factorization as the `qr` function, which you can now use.

Note that the `qr` algorithm does not ensure that all of the diagonal entries of **R** are nonnegative (in which case the factorization is not unique). If you want to force the **R** matrix to have positive diagonals, you can form a diagonal matrix **S** whose $i^{th}$ diagonal is equal to the sign of the $i^{th}$ diagonal of **R**. Then let $\widetilde{\mat{Q}}=\mat{Q}\mat{S}$ and $\widetilde{\mat{R}}=\mat{S}\mat{R}$, so that $\widetilde{\mat{Q}}\widetilde{\mat{R}}=\mat{Q}\mat{S}^2 \mat{R}=\mat{Q}\mat{R}=\mat{A}$ (since $\mat{S}^2=\mat{I}$).

c\. Use the reduced **QR** factorization of $\mat{A}$ from part (a) to find the least squares solution to 

$$
\begin{pmatrix}
2 & 3 \\
-2 & -6 \\
1 & 0
\end{pmatrix}
\begin{pmatrix}
x_1 \\
x_2
\end{pmatrix}
=
\begin{pmatrix}
3 \\
-3\\
6
\end{pmatrix}.
$$

d\. Now solve the same system using R's built-in `qr.solve` function. You'll get the same answer as in part (c) above. The point of this question is just to show you a new, useful R command that shortcuts some steps for you.

e\. If $\mat{A}$ is an $m\times n$ matrix, the null space of $\mat{A}^{\top}$ is the orthogonal complement of the column space of $\mat{A}$. Use the full **QR** factorization of $\mat{A}$ above to find a basis for the null space of $\mat{A}^{\top}$.  

### Problem 1 Solution

a\. Your solution goes here.

b\. Your solution goes here.

c\. Your solution goes here.

d\. Your solution goes here.

e\. Your solution goes here.