---
title: "Activity - Fundamentals of Linear Systems"
output:
  rmarkdown::github_document:
    html_preview: false
  header-includes:
   - \usepackage{amsmath}
---

\renewcommand{\vec}[1]{\mathbf{#1}}
\renewcommand{\mat}[1]{\mathbf{#1}}

Remember to show your work / give your reasoning, as applicable.

### Problem 1

Which of the following sets of vectors are bases for $\mathbb{R}^2$?

a. $\{(0, 1), (1, 1)\}$
b. $\{(1, 0), (0, 1), (1, 1)\}$
c. $\{(1, 0), (−1, 0)\}$
d. $\{(1, 1), (1, −1)\}$
e. $\{(1, 1), (2, 2)\}$
f. $\{(1, 2)\}$

### Problem 1 solution

Your solution goes here.

### Problem 2

What is the dimension of the intersection of the following two planes in $\mathbb{R}^3$?
$$
x + 2y − z = 0, \quad 3x − 3y + z = 0
$$

### Problem 2 Solution

Your solution goes here.

### Problem 3

Solve (by hand) the system below.

$$
\begin{pmatrix}1 & 2 & 0 \\ 3 & 2 & 4 \\ -2 & 1 & -2 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} 1 \\ 7\\ -1 \end{pmatrix}
$$

### Problem 3 Solution

Your solution goes here.

### Problem 4

Put the augmented coefficient matrix for the system of equations
$$
\begin{aligned}
x+y+z&=2\\
x+3y+3z&=0\\
x+3y+6z&=3
\end{aligned}
$$
into row echelon form.

### Problem 4 Solution

Your solution goes here.

### Problem 5

I've written a function called `eliminate` that performs Gaussian elimination in order to transform a matrix to row echelon form.

```{r}
eliminate <- function(A, tol=10^-8) {
  n = nrow(A)
  for ( j in 1:(n-1) ) {
    pivot = A[j,j]
    if (abs(pivot) < tol) stop('zero pivot encountered')
    for ( i in (j+1):n ) {
      A[i,] = A[i,] - A[i,j]/pivot * A[j,]
    }
  }
  return(A)
}
```

Demonstrate $\mathcal{O}(n^3)$ complexity by doing the following. Run the `eliminate` command on an $n \times n$ random matrix for each of $n=270,\ 540,\ 810,\ 1080,\ 1350$, saving the run time for each value of $n$. Then, use the `lm` command to fit a line to the points $(\log n,\log t)$ and find the slope.

### Problem 5 solution

Your solution goes here.

### Problem 6

Compute by hand the eigenvalues of the matrices 
$$
\mat{A}=\begin{pmatrix} 1 & 1000 \\ 0 & 1\end{pmatrix}, \qquad \widetilde{\mat{A}}=\begin{pmatrix} 1 & 1000 \\ 0.001 & 1\end{pmatrix}.
$$
Would you say that the problem of computing eigenvalues is well-conditioned or ill-conditioned? Check the condition number of $\mat{A}$ using the `kappa` command. For concreteness, use the 2-norm, though there is nothing special about that choice.

### Problem 6 Solution

Your solution goes here.