---
title: "Pset - How Computers Store Numbers"
output:
  rmarkdown::html_document:
  header-includes:
    - \usepackage{amsmath}
    - \usepackage{bm}
    - \renewcommand{\vec}[1]{\mathbf{#1}}
    - \renewcommand{\mat}[1]{\mathbf{#1}}
    - \newcommand{\exp}[1]{\mathrm{e}^{#1}}
    - \DeclareMathOperator*{\argmin}{arg\,min}
    - \DeclareMathOperator*{\float}{fl}
---

***

When you begin work during class, work with your assigned partner. Please have only one electronic device open and work on it jointly. When writing up this assignment, please remember that showing all of your work and giving your reasoning are critical parts of achieving mastery. If the course staff cannot tell how you solved a problem or finds leaps in explanation or logic, the problem is not mastered. Finally, as a matter of academic integrity, please make sure that you are positioned to honestly answer yes to these questions:

- Have I disclosed everyone with whom I collaborated on this work? (Even if it is only my assigned partner.)

- Have I made a substantive intellectual contribution to the solution of every problem?

- Am I making sure not to pass off as my own work any work that belongs to someone else?
Whether intentional or unintentional, any potential violations of academic integrity will be referred to the Honor Committee.

***

### Problem 1

Convert the following base-10 numbers to binary.

a\. 11.25

b\. 2/3

c\. 99.9

### Problem 1 Solution

a\. Your solution goes here.

b\. Your solution goes here.

c\. Your solution goes here.

### Problem 2

a\. Explain why you can determine machine epsilon on a computer using IEEE double precision and the IEEE Rounding to Nearest Rule by calculating (7/3 − 4/3) − 1. I'm not asking for (just) a conceptual explanation; you should actually calculate some things on paper to make your argument.

b\. Does (4/3 − 1/3) − 1 also give $\epsilon_{mach}$? Explain by converting to floating point numbers and carrying out the machine arithmetic.

### Problem 2 Solution

a\. Your solution goes here.

b\. Your solution goes here.

### Problem 3

Using R, compute:  1000000000000000000 + 100 - 1000000000000000000. What happens?  Show some hand calculations to explain the result.

### Problem 3 Solution

Your solution goes here.

### Problem 4

Find the smallest positive integer $i$ such that $i$ is not exactly representable using the IEEE standard in double precision; i.e., $fl(i)\neq i$.

### Problem 4 Solution

Your solution goes here.

