# Load libraries
library(knitr)
library(pracma)

# What is interpolation?
# Suppose "true" function is cosine
xgrid <- seq(from=0,to=2*pi,length=100)
ytrue <- cos(xgrid)
xsample <- seq(from=0,to=2*pi,length=4)
ysample <- cos(xsample)
ygrid <- lagrange(xsample,ysample,xgrid)
plot(xgrid,ytrue,type="l",col="black")
lines(xgrid,ygrid,col="red")

# Function vs. Taylor vs. Interpolating
f <- function(x){1/x}
t <- function(x){3-3*x+x^2}
p <- function(x){11/6 - x + 1/6*x^2}
xdata <- seq(from=1,to=3,length=3)
x <- seq(from=1,to=3,length=200)
plot(x,f(x),type="l",lwd=2)
lines(x,t(x),col="red",lwd=2)
points(xdata,f(xdata),cex=2)
py <- lagrange(xdata,f(xdata),x)
lines(x,py,col="green",lwd=2)

# Conditioning of the Vandermonde matrix
Vandermonde <- function(x) {
  n <- length(x)
  V <- outer(x, 0:(n-1), "^")
  return(V)
}
nvals <- 2^(1:8)
kappavals <- NULL
for (n in nvals){
  x <- seq(from=1,to=3,length=n)
  kappavals <- c(kappavals,kappa(Vandermonde(x)))
}
kable(cbind(nvals,kappavals))

# Solution with Vandermonde
x <- c(1,2,3,4)
y <- c(10,6,4,10)
C <- solve(Vandermonde(x),y)
C

# Vandermonde vs. Lagrange for 20 pts
set.seed(123)
n <- 20
x <- 1:n
y <- runif(n)
x0 <- 1.5
C <- solve(Vandermonde(x),y)
lagrange <- function(x,y,x0){
  ans <- 0
  for (i in 1:n){
    ans <- ans + y[i]*prod((x0-x[-i])/(x[i]-x[-i]))
  }
  return(ans)
}
lagrange(x,y,x0)

# Vandermonde vs. Lagrange speed test for 10 pts
set.seed(123)
numTrials <- 100000
n <- 10
x <- 1:n
y <- runif(n)
t1 <- system.time(
  for (i in 1:numTrials){
    C <- solve(Vandermonde(x),y)
    horner(rev(C),x0)
  }
)[3]
t2 <- system.time(
  for (i in 1:numTrials){
    lagrange(x,y,x0)
  }
)[3]
t1/t2

# Interpolation error for sin(x) with 5 pts
interperror <- function(n,plotflag=FALSE){
  x <- seq(from=0,to=2*pi,length=n)
  y <- sin(x)
  xexact <- seq(from=0,to=2*pi,length=1000)
  yexact <- sin(xexact)
  yinterp <- lagrange(x,y,xexact)
  if (plotflag==TRUE){
    plot(xexact,yexact,type="l")
    points(x,y)
    lines(xexact,yinterp,col="blue")
  }
  error  <- max(abs(yexact-yinterp))
  return(error)
}
interperror(5,plotflag=TRUE)

# Interpolation error for sin(x) as a function of n
nvec <- 2:20
errorvec <- NULL
for (n in nvec){
  errorvec <- c(errorvec,interperror(n))
}
orderofmag <- round(log10(errorvec))
plot(nvec,orderofmag)
